# Generated by Django 4.2.5 on 2023-10-03 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='article',
            name='topic',
        ),
        migrations.AlterField(
            model_name='category',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='categories', to='homepage.topic'),
        ),
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.topic'),
        ),
    ]
