# Generated by Django 4.2.5 on 2024-01-07 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_article_image_bewertung'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auswertung',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lesbarkeit', models.IntegerField()),
                ('informationsgehalt', models.IntegerField()),
                ('qualitaet', models.IntegerField()),
                ('gesamt', models.IntegerField()),
                ('anzahlauswertungen', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.article')),
            ],
        ),
    ]
