# Generated by Django 4.2.5 on 2024-01-24 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0007_article_sichtbar_delete_auswertung'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bewertung',
            name='gesamt',
        ),
        migrations.RemoveField(
            model_name='bewertung',
            name='informationsgehalt',
        ),
        migrations.RemoveField(
            model_name='bewertung',
            name='lesbarkeit',
        ),
        migrations.RemoveField(
            model_name='bewertung',
            name='qualitaet',
        ),
        migrations.AddField(
            model_name='bewertung',
            name='rating',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bewertung',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='sichtbar',
            field=models.BooleanField(default=False),
        ),
    ]
