# Generated by Django 4.2.5 on 2024-02-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_bewertung_richtig_alter_bewertung_identifiziert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='category',
            name='topics',
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
