# Generated by Django 4.2.5 on 2024-02-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_alter_article_article_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='anzahl',
            field=models.IntegerField(default=0),
        ),
    ]
