# Generated by Django 4.2.5 on 2024-02-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_article_anzahl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='anzahl',
            new_name='bewertungen',
        ),
    ]
